### ISSUE TITLE
how to modify the caffe path

### ISSUE THREAD

**Issue by berylyellow** [kmaninis/OSVOS-caffe#10]
hi，  can I install caffe by docker？And how to modify the caffe path in set_params.m?

**Comment by scaelles** [comment]
Hello,
We have not tried to use this repository under docker. In my personal experience, I did once install Caffe in a docker file and it worked. Regarding the Caffe path, you can just set the parameter `osvos_params.caffe_path` in `set_params.m` to your path. Finally, I would strongly encourage you to use the [Tensorflow](https://github.com/scaelles/OSVOS-TensorFlow) or [Pytorch](https://github.com/kmaninis/OSVOS-PyTorch) ports as they are much easier to set up.
