### ISSUE TITLE
What are the GPU memory requirements to run this program?

### ISSUE THREAD

**Issue by kaisark** [kmaninis/OSVOS-caffe#2]
What are the GPU memory requirements to run this program?

Can this code run on a Nvidia TX1 with 4GB of memory?

**Comment by MathLee** [comment]
Hello! The program needs 8GB memory to run. And I run this code on a Nvidia Titan XP with 12GB of memory.






At 2018-02-14 10:46:19, "kaisar khatak" <notifications@github.com> wrote:


What are the GPU memory requirements to run this program?

Can this code run on a Nvidia TX1 with 4GB of memory?

**Comment by kaisark** [comment]
Thanks for the quick response. Maybe, I can throw the code up onto an AWS P2 instance.

Is matcaffe (matlab) required to run the demo? Matlab is not free...

**Comment by scaelles** [comment]
Matlab is required to run this demo. If you don't have a license, I would recommend you to check the Pytorch or Tensorflow versions.
