### ISSUE TITLE
weight of the deconvolutional layer

### ISSUE THREAD

**Issue by haoliyoupai09** [kmaninis/OSVOS-caffe#6]
The weight_filler in the deconvolutional layer is missed and the lr_mult is set to be 0. I wonder whether it means that the weight of the deconvolutional layer is initialized in a default way and the weight is not updated after the initialization. If this is the case, why not update the weight? Any help is appreciated, and looking forward to your early reply.

**Comment by kmaninis** [comment]
Hi. When training the parent model, we set and freeze the weights of the deconvolutional layer to bilinear upsampling (see link below). For the online training scripts, we simply copy those weights and use them unaltered. It is possible to train these weights, but our results were practically the same.

https://github.com/kmaninis/OSVOS-caffe/blob/b12ee186ac5f2e36713c75c6847add21f6e13b4c/src/parent/solve_cluster.py#L50

**Comment by haoliyoupai09** [comment]
Oh, I see. Thanks a lot.
