### ISSUE TITLE
question about Fast Bilateral Solver (FBS).

### ISSUE THREAD

**Issue by ARQlalala** [kmaninis/OSVOS-caffe#7]
Hello,
Fast Bilateral Solver method in your model was used to refine edge, I wonder how you employ it in your project. Thank you very much! 
![image](https://user-images.githubusercontent.com/22908378/43406408-b9282c84-944e-11e8-8094-7c6fcad5db25.png)

**Comment by kmaninis** [comment]
Hi. Instead of snapping the CNN output (foreground probabilities) to superpixels, we use it as input to the [bilateral solver](https://github.com/poolio/bilateral_solver), to refine - as you said - the edge regions.
