### ISSUE TITLE
parent network training

### ISSUE THREAD

**Issue by rinawhale** [kmaninis/OSVOS-caffe#8]
Hi, 
when I train parent network, I got three models: osvos_parent_step1_iter_5000.caffemodel / osvos_parent_step1_iter_10000.caffemodel / osvos_parent_step1_iter_15000.caffemodel; I am confused about the difference between  these three models I get and the model OSVOS_parent.caffemodel can be downloaded? Thank you!

**Comment by MathLee** [comment]
Hi,

The difference between osvos_parent_step1_iter_5000.caffemodel and 
osvos_parent_step1_iter_10000.caffemodel and 
osvos_parent_step1_iter_15000.caffemodel is the 
osvos_parent_step1_iter_5000.caffemodel is training the model 5000 iters 
and osvos_parent_step1_iter_10000.caffemodel is training the model 10000 
iters. And you can download the model OSVOS_parent.caffemodel from 
https://github.com/kmaninis/OSVOS-caffe and the link is in Installation/ 
Download the parent model fromhere 
<https://data.vision.ee.ethz.ch/kmaninis/share/OSVOS/Downloads/models/OSVOS_parent_model.zip>(55 
MB) and put it under|models/|. I hope this is helpful to you.


在 2019年01月16日 20:25, rinawhale 写道:
